### ISSUE TITLE
Jest fails with "Cannot find module"?

### ISSUE THREAD

**Issue by emjimadhu** [Rouche/vue-ts-template#5]
This repo helped me aa lot. Thank you so much. Everything is worrking except `jest`.

example.spec.ts
```
import { shallowMount } from '@vue/test-utils';
import HelloWorld from '@/components/hello-world/hello-world.component';

describe('HelloWorld.vue', () => {
	it('renders props.msg when passed', () => {
		const message = 'new message';
		const wrapper = shallowMount(HelloWorld, {
			propsData: {
				msg: message
			}
		});
		expect(wrapper.text()).toMatch(message);
	});
});
```

Error:
```
$ vue-cli-service test:unit
 FAIL  tests/unit/example.spec.ts
  ● Test suite failed to run

    Cannot find module './hello-world.component.html?style=./hello-world.component.scss' from 'hello-world.component.ts'

      3 | } from 'vue-property-decorator';
      4 | 
    > 5 | import WithRender from './hello-world.component.html?style=./hello-world.component.scss';
        | ^
      6 | 
      7 | @WithRender
      8 | @Component

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (src/components/hello-world/hello-world.component.ts:5:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.778s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Can you please add a sample for jest with your implementation? Thaanks in advance!

**Comment by Rouche** [comment]
Hello @emjimadhu 

Sadly im no longer working with Vue.js. And i never used Jest.

I wish i could help but my current work is taking too much time. This project is only an example project by the way. 

You should check this project: **https://github.com/Rouche/vue-auto-tmpl-loader**

You no longer need those WithRender at all. It will add your files automatically if they are named correct;ly.

**Comment by emjimadhu** [comment]
@Rouche Thank you so much for trying to help. I will look into it. Thanks.
